### ISSUE TITLE
Ticker format for Non-US exchanges 

### ISSUE THREAD

**Issue by haohua** [business-science/tidyquant#27]
Hi Matt, 

I have a ticker formatting issue for non-us listed companies. 

For China-A share, yahoo.finance/google.finance requires the "Ticker + Exchange" info in order to get the price data. For US listed companies, there is no such requirement.  Moreover, for "key.ratios", Morningstar requires the original "Ticker" to retrieve the data. 
So we may need a ticker formatting method to adjust for different exchange, different data request. 

Here is an example: ticker "200725" in Shenzhen exchange 

what works:
prices  <- tidyquant::tq_get(x = "200725.SZ", get = "stock.prices", from = " 1990-01-01")
what doesn't work:
 prices  <- tidyquant::tq_get(x = "200725", get = "stock.prices", from = " 1990-01-01")

what works:
key-ratio url link:
http://financials.morningstar.com/finan/ajax/exportKR2CSV.html?&callback=?&t=XSHE:200725&region=chn&culture=en-US&cur=&order=asc

please let me know your thoughts. 

thanks
andy

**Comment by mdancho84** [comment]
This is a tough one because the underlying data is coming from two different sources. For stock.prices, the data is coming from Yahoo! Finance. The key.ratios are coming from Morningstar. Because of the different sources, input parameters for the ticker are different. I'm not entirely sure what we can do for the formatting since there is likely to be a lot of cases that are not easy to handle programmatically.

**Comment by haohua** [comment]
you are right. I'll start off some testing branch to see if there is quick solution. 
Right now, inside of the keyratio request, it is also getting stock.prices, and that's the tricky part.

**Comment by mdancho84** [comment]
Ah, yes. I do that to calculate lagging PE ratios. This is a bit tricky. Let me know what you find out.

**Comment by vikram-rawat** [comment]
Is there any way to get indian stock market here as well.
