### ISSUE TITLE
Charting TTR functions in Tidyquant

### ISSUE THREAD

**Issue by moraesmark** [business-science/tidyquant#70]
Dear Matt,

This isn't a bug post issue, rather a question, on whether documentation exists for grouping TTR indicators with the price plot. i.e. is it possible to **plot**  and/or **overlay** stock prices, along with macd, volume and obv, grouped up, to make the visualization more coherent, within the Tidyquant-verse. 

Cheers,

Mark

Edit: This question was asked, since I can't seem to implement the Quandl xts objects into Quantmod's chartseries. And the chartseries in Quantmod, allows the overlay of TTR functions onto the stock prices, therefore making a much more coherent visualization.

**Comment by mdancho84** [comment]
Hi Mark,
The short answer is that SMA and the other moving averages and Bollinger Bands are currently supported with the `geom_ma()` and `geom_bbands()` ggplot geometries. We don't have the other TTR functions such as MACD and others incorporated yet. There's quite a bit that goes into it because of the multiple charts for volume and other diagnostics. However, there are plans to incorporate more of this functionality. Davis and I hope to do this soon.
-Matt

**Comment by moraesmark** [comment]
Thanks Matt, 

Once again, much appreciative of every bit of effort that goes into Tidyquant!

Cheers
